# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_studentquizresult_personal_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizresult',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentquizresult',
            name='questions_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
