# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20171210_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquizresult',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
