# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-20 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_quiz_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('freetext', 'Free text')], default='single_choice', max_length=50),
        ),
    ]
